[phases.setup]
nixPkgs = ['nodejs', 'ffmpeg-full', 'sox']

[phases.install]
cmds = ['npm install']  # Changed from npm ci

[phases.build]
cmds = ['echo "AudioCraft Studio build complete"']

[start]
cmd = 'node server.js'